### PR TITLE
27 add links to syllabus

### PR DESCRIPTION
**Pull request by Vladimir4932**

### CODE REVIEW

**Comment by breslavsky** [comment]
@Vladimir4932 please check we have conflicts.

**Comment by Vladimir4932** [comment]
> @Vladimir4932 please check we have conflicts.

I see. checking.

**Comment by Vladimir4932** [comment]
@breslavsky done. check, please

**Comment by breslavsky** [comment]
No, please check again.

Check `LP.md` how it works now.

**Comment by Vladimir4932** [comment]
> 

i see. doing.

**Comment by Vladimir4932** [comment]
@breslavsky I should add links in **README.md** only. Or in the **LP.md** too?

**Comment by Vladimir4932** [comment]
@breslavsky check, please. All links are done without **deep_cypress.mm** **fake_data.mm**. Do you think I should do it in this pull request?

**Comment by breslavsky** [comment]
All right, just remove `README.md` from changes.

**Comment by Vladimir4932** [comment]
Done

**Pull request merged**
