### PR TITLE
Rewrite install_cypress and write_own_test

### PR DESCRIPTION
**Pull request by Vladimir4932**

### CODE REVIEW

**Comment by Vladimir4932** [comment]
@breslavsky check please. Is it a needed point?

**Comment by breslavsky** [comment]
Yes, it is pull request.

Please check tutorial https://md.epic1h.com/cypress_test_flight

In step install cypress we don't need add scripts command.

We need record new videos because old are not relevant.

**Comment by Vladimir4932** [comment]
@breslavsky video was fixed. check please

**Comment by breslavsky** [comment]
Super nice!

**Comment by breslavsky** [comment]
@Vladimir4932 please check your new videos here https://md.epic1h.com/cypress_test_flight

**Pull request merged**
